/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anirban
 */
import java.util.*;
import javax.script.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class messentry extends javax.swing.JFrame {
    
     private int x,y;
     private String time,currentDate;
     public String str="0",str1="0",str3; 
    /**
     * Creates new form messentry
     */
    public void fix(String str1, String str2) {
        
        str3=str1;
        lblname.setText(str2);
        lbldate.setText(dateformat());
    }

    public String dateformat() {

        Calendar javaCalendar;
        javaCalendar = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:MM");
        time= sdf.format(javaCalendar.getTime());
        currentDate = javaCalendar.get(Calendar.DATE) + "/" + (javaCalendar.get(Calendar.MONTH) + 1) + "/" + javaCalendar.get(Calendar.YEAR);
       // System.out.print(currentDate +"and"+time+"  ");
        return (currentDate);


    }

    public void add() {
    }

    public messentry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblname = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lblcost = new javax.swing.JLabel();
        costtextfield = new javax.swing.JTextField();
        lblextra = new javax.swing.JLabel();
        extratextfield = new javax.swing.JTextField();
        lblamount = new javax.swing.JLabel();
        submitbutton = new javax.swing.JButton();
        lblheading = new javax.swing.JLabel();
        amounttextfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 420));
        setResizable(false);

        lblname.setBackground(new java.awt.Color(255, 255, 255));
        lblname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblname.setText("NAME");
        lblname.setToolTipText("");

        lbldate.setBackground(new java.awt.Color(255, 252, 252));
        lbldate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbldate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldate.setText("DATE");

        lblcost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblcost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcost.setText("COST");

        costtextfield.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        costtextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblextra.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblextra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblextra.setText("EXTRA");

        extratextfield.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        extratextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        extratextfield.setToolTipText("");
        extratextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extratextfieldActionPerformed(evt);
            }
        });
        extratextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                extratextfieldKeyPressed(evt);
            }
        });

        lblamount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblamount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblamount.setText("AMOUNT");

        submitbutton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        submitbutton.setText("SUBMIT");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        lblheading.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblheading.setText("DAILY BILL");
        lblheading.setToolTipText("");

        amounttextfield.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        amounttextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amounttextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amounttextfieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblheading, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(lblcost, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(costtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(491, 491, 491)
                        .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(327, 327, 327)
                                .addComponent(lblextra, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(377, 377, 377)
                                .addComponent(lblamount)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(extratextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(amounttextfield))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblheading, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcost, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblextra))
                    .addComponent(extratextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblamount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amounttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        costtextfield.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        x=Integer.parseInt(amounttextfield.getText());
        String messid="gmess";
        
        try{
            
            System.out.println(str3);
            connection con = new connection();
            String sql = "Insert into eat values('"+messid+"','"+str3+"','"+time+"','"+x+"','"+currentDate+"')";
            con.stmt=con.conn.createStatement();
            con.stmt.execute(sql);
            JOptionPane.showMessageDialog(null,"Thanks");
            {
                
            }
        }
        catch(Exception ex){
           //ex.printStackTrace();
            System.out.print(ex);
        }
        
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void amounttextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amounttextfieldKeyPressed
            
    }//GEN-LAST:event_amounttextfieldKeyPressed

    private void extratextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extratextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extratextfieldActionPerformed

    private void extratextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_extratextfieldKeyPressed
        x = Integer.parseInt(costtextfield.getText());
        int i= evt.getKeyCode();
       
        try{
        if(i!=8){
        str=str1+(i-48);
        str1=str;
        str="0";
        y=x+(Integer.parseInt(str1));
        amounttextfield.setText(y+"");
        }else{
            extratextfield.setText(null);
            amounttextfield.setText(x+"");
            str1="0";
                       
        }
        }catch(Exception e){
            System.out.print(e);
        }
        
    }//GEN-LAST:event_extratextfieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(messentry.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(messentry.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(messentry.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(messentry.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new messentry().setVisible(true);
            }
        });
        
        
    }   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amounttextfield;
    private javax.swing.JTextField costtextfield;
    private javax.swing.JTextField extratextfield;
    private javax.swing.JLabel lblamount;
    private javax.swing.JLabel lblcost;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblextra;
    private javax.swing.JLabel lblheading;
    private javax.swing.JLabel lblname;
    private javax.swing.JButton submitbutton;
    // End of variables declaration//GEN-END:variables

}
