/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anirban
 */
import java.util.*;
import javax.script.*;

public class messentry extends javax.swing.JFrame {

    /**
     * Creates new form messentry
     */
    public int x,y;
    public void fix(String str2) {
        lblname.setText(str2);
        lbldate.setText(dateformat());
        }
    
    public String dateformat(){
     
        Calendar javaCalendar;
        String currentDate ;
        javaCalendar = Calendar.getInstance();
        currentDate = javaCalendar.get(Calendar.DATE) + "/" + (javaCalendar.get(Calendar.MONTH)+1) + "/" + javaCalendar.get(Calendar.YEAR);
        return(currentDate);
        
         
    }
    public void add(){
        
    }
    public messentry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblname = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lblcost = new javax.swing.JLabel();
        costtextfield = new javax.swing.JTextField();
        lblextra = new javax.swing.JLabel();
        extratextfield = new javax.swing.JTextField();
        lblamount = new javax.swing.JLabel();
        amounttextfield = new javax.swing.JTextField();
        submitbutton = new javax.swing.JButton();
        lblheading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 420));
        setResizable(false);

        lblname.setBackground(new java.awt.Color(255, 255, 255));
        lblname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblname.setText("NAME");
        lblname.setToolTipText("");

        lbldate.setBackground(new java.awt.Color(255, 252, 252));
        lbldate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbldate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldate.setText("DATE");

        lblcost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblcost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcost.setText("COST");

        costtextfield.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        costtextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblextra.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblextra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblextra.setText("EXTRA");

        extratextfield.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        extratextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        extratextfield.setText("0");
        extratextfield.setToolTipText("");

        lblamount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblamount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblamount.setText("AMOUNT");

        amounttextfield.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        amounttextfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amounttextfield.setToolTipText("");
        amounttextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amounttextfieldActionPerformed(evt);
            }
        });
        amounttextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amounttextfieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amounttextfieldKeyTyped(evt);
            }
        });

        submitbutton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        submitbutton.setText("SUBMIT");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        lblheading.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblheading.setText("DAILY BILL");
        lblheading.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblheading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblcost, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblextra, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(224, 224, 224)
                                        .addComponent(lblamount, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                                .addGap(33, 33, 33)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(submitbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(amounttextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(extratextfield)
                            .addComponent(costtextfield))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblheading, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costtextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblcost, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extratextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(lblextra))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblamount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amounttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        costtextfield.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amounttextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amounttextfieldActionPerformed
            
    }//GEN-LAST:event_amounttextfieldActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
       
            entry e=new entry();
            String s=e.str1;
            connection conn=new connection();
            
            String sql="Insert into eat values()";
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void amounttextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amounttextfieldKeyPressed
             while(costtextfield.getText()!=null || extratextfield.getText()!=null){
             x= Integer.parseInt(costtextfield.getText());
           /* y= Integer.parseInt(extratextfield.getText());
             int  z=x+y;*/
             amounttextfield.setText(x+"");
             
        }
    }//GEN-LAST:event_amounttextfieldKeyPressed

    private void amounttextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amounttextfieldKeyTyped
             x= Integer.parseInt(costtextfield.getText());
             y= Integer.parseInt(extratextfield.getText());
             int  z=x+y;
             amounttextfield.setText(z+ "");
    }//GEN-LAST:event_amounttextfieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(messentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(messentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(messentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(messentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new messentry().setVisible(true);
            }
        });
        
        
    }   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amounttextfield;
    private javax.swing.JTextField costtextfield;
    private javax.swing.JTextField extratextfield;
    private javax.swing.JLabel lblamount;
    private javax.swing.JLabel lblcost;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblextra;
    private javax.swing.JLabel lblheading;
    private javax.swing.JLabel lblname;
    private javax.swing.JButton submitbutton;
    // End of variables declaration//GEN-END:variables

}
